### ISSUE TITLE
有没有办法,让数字显示在上方啊,求指导

### ISSUE THREAD

**Issue by yizems** [Sanjay-F/RulerView#1]

**Comment by Sanjay-F** [comment]
啊？什么意思，数日显示在上方？
具体是怎样的？

是刻度在下面，数字在对应的线的上方吗？

**Comment by yizems** [comment]
就是这样,把 下面的数字换到上面去

发自网易邮箱大师

在2016年11月10日 11:13， Sanjay_fnotifications@github.com写道：

啊？什么意思，数日显示在上方？
具体是怎样的？

是刻度在下面，数字在对应的线的上方吗？

**Comment by yizems** [comment]
https://ooo.0o0.ooo/2016/11/10/5823e6b2763b3.png 图片

**Comment by Sanjay-F** [comment]
@yizeliang  这个项目好久没维护了，后来改的代码都没更新上传。。。

你去到drawUpMode(）函数把canvas.drawText(）里面的Y位置坐标修改成ry + mLineHeighMax  试下看效果。

**Comment by yizems** [comment]
谢谢了,你给我提供了一种解决方法,十分感谢,..虽然不是那么做的,但是 我的确学到了许多东西,3Q

发自网易邮箱大师

在2016年11月10日 11:30， Sanjay_fnotifications@github.com写道：

@yizeliang 这个项目好久没维护了，后来改的代码都没更新上传。。。

你去到drawUpMode(）函数把canvas.drawText(）里面的Y位置坐标修改成ry + mLineHeighMax 试下看效果。

**Comment by Sanjay-F** [comment]
@yizeliang  这么6,用什么招式实现的？

**Comment by yizems** [comment]
@Sanjay-F 其实就是ondraw 画 数字和竖线,改下位置就好了

**Comment by Sanjay-F** [comment]
@yizeliang  机智如你，那我关了这问题

**Comment by yizems** [comment]
OK,3Q

发自网易邮箱大师

在2016年11月14日 11:27， Sanjay_fnotifications@github.com写道：

@yizeliang 机智如你，那我关了这问题
